# volumes:
#   db-data:

services:
  db:
    image: postgres:16.3-bookworm
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: mynuxtshop
      POSTGRES_USER: mynuxtshop
      POSTGRES_DB: mynuxtshop
    # volumes:
    #   - db-data:/var/lib/postgresql/dataresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
