volumes:
  db-data-production:

services:
  nuxtapp:
    image: nuxtapp
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db
    ports:
      - 3000:3000

  db:
    image: postgres:16.3-bookworm
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: mynuxtshop
      POSTGRES_USER: mynuxtshop
      POSTGRES_DB: mynuxtshop
    volumes:
      - db-data-production:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
